site_name: dcurves Documentation

plugins: 
  - mkdocstrings:
      handlers:
          python:
            paths: [dcurves]

theme: 
  name: "material"

nav:
  - dcurves Docs: README.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - reference.md
  - explanation.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
