name: UV CI Pipeline

on:
  push:
    branches:
      - '*'  # Run on all branches
    tags:
      - '*'
  pull_request:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Create virtual environment and install dependencies
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install -e ".[dev]"
          # Explicitly install scikit-learn to ensure it's available
          uv pip install scikit-learn

      - name: Run Tests
        run: |
          source .venv/bin/activate
          pytest

  publish-to-testpypi:
    name: Publish to Test PyPI
    # Run on all branches
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv and dependencies
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          uv venv
          source .venv/bin/activate
          uv pip install tomli

      - name: Get package name and version
        id: get-package-info
        run: |
          source .venv/bin/activate
          python -c "
          import tomli
          with open('pyproject.toml', 'rb') as f:
              data = tomli.load(f)
          print(f'PACKAGE_NAME={data[\"project\"][\"name\"]}')
          print(f'VERSION={data[\"project\"][\"version\"]}')
          " >> $GITHUB_ENV

      - name: Check version on Test PyPI
        id: version-check
        run: |
          RESPONSE=$(curl -s https://test.pypi.org/pypi/${{ env.PACKAGE_NAME }}/json || echo "error")
          if [ "$RESPONSE" != "error" ] && echo "$RESPONSE" | jq -r '.releases | keys' | grep -q "\"${{ env.VERSION }}\""; then
            echo "Version ${{ env.VERSION }} already exists on Test PyPI."
            echo "skip=true" >> $GITHUB_ENV
          else
            echo "Version ${{ env.VERSION }} does not exist on Test PyPI. Proceeding with publish."
            echo "skip=false" >> $GITHUB_ENV
          fi

      - name: Clean dist directory
        if: env.skip != 'true'
        run: |
          rm -rf dist/*

      - name: Build package
        if: env.skip != 'true'
        run: |
          source .venv/bin/activate
          uv build

      - name: Publish to Test PyPI
        if: env.skip != 'true'
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          source .venv/bin/activate
          uv publish --publish-url https://test.pypi.org/legacy/

  publish-to-pypi:
    name: Publish to PyPI
    if: startsWith(github.ref, 'refs/tags/')
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv and dependencies
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          uv venv
          source .venv/bin/activate
          uv pip install tomli

      - name: Get package name and version
        id: get-package-info
        run: |
          source .venv/bin/activate
          python -c "
          import tomli
          with open('pyproject.toml', 'rb') as f:
              data = tomli.load(f)
          print(f'PACKAGE_NAME={data[\"project\"][\"name\"]}')
          print(f'VERSION={data[\"project\"][\"version\"]}')
          " >> $GITHUB_ENV

      - name: Check version on PyPI
        id: version-check
        run: |
          RESPONSE=$(curl -s https://pypi.org/pypi/${{ env.PACKAGE_NAME }}/json || echo "error")
          if [ "$RESPONSE" != "error" ] && echo "$RESPONSE" | jq -r '.releases | keys' | grep -q "\"${{ env.VERSION }}\""; then
            echo "Version ${{ env.VERSION }} already exists on PyPI."
            echo "skip=true" >> $GITHUB_ENV
          else
            echo "Version ${{ env.VERSION }} does not exist on PyPI. Proceeding with publish."
            echo "skip=false" >> $GITHUB_ENV
          fi

      - name: Clean dist directory
        if: env.skip != 'true'
        run: |
          rm -rf dist/*

      - name: Build package
        if: env.skip != 'true'
        run: |
          source .venv/bin/activate
          uv build

      - name: Publish to PyPI
        if: env.skip != 'true'
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          source .venv/bin/activate
          uv publish --publish-url https://upload.pypi.org/legacy/